### PR TITLE
login fix for solarlog firmware >= 6.1.1

### LINKED ISSUE #221: ACCESS DENIED nach Firmwareupdate, Solar-Log Base 15  6.1.0 Build 163 - 12.04.2024
Nach dem letzten Update des SolarLog Base 15 auf die Version 6.1.0 Build 163, werden keine Objekte mehr aktualisiert, wenn der Login passwortgeschützt ist. Im Log wird "ACCESS DENIED" wiederholt gemeldet.

**To Reproduce**  
1. Mit Passwortschutz -> ACCESS DENIED
2. Ohne Passwortschutz -> scheinbar ohne Fehler

**Screenshots & Logfiles**  
[SolarLog_DebugLog.txt](https://github.com/user-attachments/files/15511298/SolarLog_DebugLog.txt)
[SolarLog_DebugLog_ohne_Passwort.txt](https://github.com/user-attachments/files/15511299/SolarLog_DebugLog_ohne_Passwort.txt)

**Versions:**  
 - Adapter version: <2.3.0>
Plattform: docker (official image - v9.1.2)
RAM: 15.5 GB
Node.js: v18.20.3
NPM: 10.8.0

### PR DESCRIPTION
**Pull request by it-busch**
Fixes #221

### CODE REVIEW

**Comment by it-busch** [comment]
@Apollon77 Can you review it?

**Comment by mcm1957** [comment]
@it-busch 

Thanks for the fix. I've reverted all changes related to version numberiung - this data will be updated during release processing.

**Please let me know, if your change will work with older firmware too.** I do not see a check whether the new encrypted process should be used or the current one.

File: main.js [hunk 1]
```diff
@@ -165,8 +166,9 @@ async function main() {
     forecast = !!adapter.config.forecast;
     historic = !!adapter.config.historic;
     histCRON = `${adapter.config.histmin} ${adapter.config.histhour} * * *`
+    userName = `user`;
     userPass = !!adapter.config.userpass;
-    loginData = `u=user&p=${adapter.config.userpw}`;
+    userPw = adapter.config.userpw;
```
Comment (it-busch) [inline main.js]: loginData will be created after encryption check

**Review by it-busch — COMMENTED** [review]
Comments to check logic

**Comment by it-busch** [comment]
@mcm1957 

Thanks for review.

Sorry, this is my first public GitHub PR. 
I just had to fix this SolarLog bug, so why not share it with the community :)

I usually only have private projects.

**Comment by mcm1957** [comment]
Thanks for explanation. As I do not know the protiocol this was hard to detect.
I'll release a test version hopefully today.
